"""Add quality tracking columns

Revision ID: fc4fc8e132ee
Revises: b0db713c0cc1
Create Date: 2026-01-08 17:59:26.302150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4fc8e132ee'
down_revision: Union[str, Sequence[str], None] = 'b0db713c0cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_content', sa.Column('model_used', sa.String(), nullable=True))
    op.add_column('generated_content', sa.Column('validation_passed', sa.Boolean(), nullable=True))
    op.add_column('generated_content', sa.Column('regeneration_count', sa.Integer(), nullable=True))
    op.add_column('generated_content', sa.Column('char_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_content', 'char_count')
    op.drop_column('generated_content', 'regeneration_count')
    op.drop_column('generated_content', 'validation_passed')
    op.drop_column('generated_content', 'model_used')
    # ### end Alembic commands ###
